--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-04-24 15:23:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 49276)
-- Name: person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.person (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255),
    username character varying(255)
);


ALTER TABLE public.person OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 49275)
-- Name: person_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 57370)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255),
    role character varying(255),
    username character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 57369)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4784 (class 0 OID 49276)
-- Dependencies: 214
-- Data for Name: person; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.person (id, email, password, username) FROM stdin;
1	Julius21@hotmail.com	_Jz_1YHzYpS7BxF	Akeem.Bailey
2	Lacey_Gutmann@yahoo.com	klbjk4js_6lSFWP	Antone.Koepp39
3	Tyson.Stamm@yahoo.com	IUrOqcfAY_8l7uo	Camren_Miller
4	Roselyn_Nikolaus5@yahoo.com	j5_N8HXMpgiEom2	Damian.McClure99
\.


--
-- TOC entry 4786 (class 0 OID 57370)
-- Dependencies: 216
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, password, role, username) FROM stdin;
1	marieclara@gmail.com	$2a$10$KblOhoEEP7gQh3uXbS0P4e.D0Wgxhx8YtQAkb5u67HF2idHFk5T.S	ROLE_USER	Juanita_Daniel
2	marieclara@yahoomail.com	$2a$10$oWDp3j0iOW49LGc6C3iO1O.UmqC/rSApeFt21welEztZoYN0dZ3j2	ROLE_USER	Nya.Beier78
3	myrcella@yahoomail.com	$2a$10$/u3Dnef4ow7MluZC7iJtxeQNJfPEA01y38h4cUZpAJegzsn6/GfUy	ROLE_USER	Heath.Boyer
4	Golden.Stanton@yahoo.com	$2a$10$ypg.d1rRLCo5TtZfgBnSveSs.joJ2FEEDd3u9OEz9P9kpHHdL5ZLa	ADMIN	Aurelia_Rempel
5	Dorthy_Wilderman@hotmail.com	$2a$10$.Ydw4qzrHGkoj/Gv0.KSe.ETcGae7w9tkAYNIttnWZvoJI/1Yexzy	ADMIN	Kelli_McKenzie17
6	Abe4@gmail.com	$2a$10$ndqTv2Tk47CcqqVXnOUJ1.jFrtYqNrB9RFovv1s76vK0n4tXk60OO	ADMIN	Tommie17
7	ulrich@gmail	$2a$10$m10.00P5yjcvGKDiosvTfe/dd1RJpb10lZs7/z6n12viK.eLyC.PW	ADMIN	ulrich
8	ulrich2@gmail	$2a$10$UqWE0WN.f6DPBCVq5p7d.usD/Kgu9cCxE/hKhK3aCz18804dfqp0C	ADMIN	ulrich2
\.


--
-- TOC entry 4792 (class 0 OID 0)
-- Dependencies: 213
-- Name: person_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.person_id_seq', 4, true);


--
-- TOC entry 4793 (class 0 OID 0)
-- Dependencies: 215
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 8, true);


--
-- TOC entry 4635 (class 2606 OID 49282)
-- Name: person person_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.person
    ADD CONSTRAINT person_pkey PRIMARY KEY (id);


--
-- TOC entry 4637 (class 2606 OID 57376)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


-- Completed on 2025-04-24 15:23:54

--
-- PostgreSQL database dump complete
--

