--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-04-24 17:42:34

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 65606)
-- Name: comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comment (
    id bigint NOT NULL,
    comment character varying(255) NOT NULL,
    date date,
    "post-id" bigint
);


ALTER TABLE public.comment OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 65605)
-- Name: comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 65587)
-- Name: post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.post (
    id bigint NOT NULL,
    content character varying(255) NOT NULL,
    date date NOT NULL,
    title character varying(255) NOT NULL
);


ALTER TABLE public.post OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 65586)
-- Name: post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4799 (class 0 OID 65606)
-- Dependencies: 220
-- Data for Name: comment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comment (id, comment, date, "post-id") FROM stdin;
1	Très bon article !	2025-04-23	1
3	je suis  impressionné 	2025-04-23	3
4	Que de bonne nouvelles 	2025-04-24	3
5	Que de bonne nouvelles 	2025-04-23	3
6	j'adore votre manière d'aborder les faits de la société 	2025-05-23	4
\.


--
-- TOC entry 4797 (class 0 OID 65587)
-- Dependencies: 218
-- Data for Name: post; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.post (id, content, date, title) FROM stdin;
1	Voici le contenu	2025-04-22	Un titre
3	son adolesence , sa joie de vivre et ses amitiés 	2025-04-22	Les aventures de Binta
4	son adolesence , sa joie de vivre et ses amitiés 	2025-04-25	Les Divers
5	Une passion que je partage dejà depuis pas très longtemps que je pense qu'ells peut me propulsé au faite 	2025-04-25	Mon amour pour le Code
\.


--
-- TOC entry 4805 (class 0 OID 0)
-- Dependencies: 219
-- Name: comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comment_id_seq', 6, true);


--
-- TOC entry 4806 (class 0 OID 0)
-- Dependencies: 217
-- Name: post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.post_id_seq', 5, true);


--
-- TOC entry 4649 (class 2606 OID 65610)
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);


--
-- TOC entry 4647 (class 2606 OID 65593)
-- Name: post post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.post
    ADD CONSTRAINT post_pkey PRIMARY KEY (id);


--
-- TOC entry 4650 (class 2606 OID 65611)
-- Name: comment fk4ietgiuqg7yljtgtf7ogghyrw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment
    ADD CONSTRAINT fk4ietgiuqg7yljtgtf7ogghyrw FOREIGN KEY ("post-id") REFERENCES public.post(id);


-- Completed on 2025-04-24 17:42:34

--
-- PostgreSQL database dump complete
--

